In [1]:
import numpy as np
import scipy as sp
import math

In [16]:
# Podaj najmniejszą z wartości własnych dla macierzy A  z dokładnością do 5 miejsc po przecinku
A = np.array([[38, -10, 1], [-10, 19, -38], [1, -38, 110]])
A1 = np.array([[18, -35, 15], [-35, 93, -4], [15, -4, 38]])
print(A1)
eig = np.linalg.eigvals(A1)
print(eig)
print(np.min(eig))

[[ 18 -35  15]
 [-35  93  -4]
 [ 15  -4  38]]
[1.08036600e+02 1.10750733e-02 4.09523248e+01]
0.011075073332976701


In [3]:
# Podaj normę Frobeniusa macierzy A z dokładności do 5 miejsc po przecinku.
B = np.array([[3, 5, -8, -5], [-3, 9, 4, -4], [-4, 2, -6, 1], [-5, 8, 0, -10]])
print(A)
frob = np.linalg.norm(B, 'fro')
print(frob)

[[ 38 -10   1]
 [-10  19 -38]
 [  1 -38 110]]
22.15851980616034


In [4]:
# Podaj błąd zaokrąglenia dla zadania A +b - A z dokładności do 20 miejsc po przecinku dla:
A = 374787
b = 0.0625
c = A+b-A
print("{:.20f}".format(c-b))

0.00000000000000000000


In [5]:
# Podaj wartość 0-go elementu rozwązania, z dokładnością do 5 miejsca po przecinku, równania Ax=b
A = np.array([[-6,-7],[5,-7]])
b= np.array([3,38])

l, u = sp.linalg.lu(A, permute_l=True)

y = np.linalg.solve(l, b)
wyn = sp.linalg.solve_triangular(u, y)
print(wyn)

r = np.linalg.solve(A, b)
print(r)

[ 3.18181818 -3.15584416]
[ 3.18181818 -3.15584416]


In [6]:
#Podaj wartość normy residum dla rozwiązania układu równań Ax=b z dokładnością do 5 miejsc po przecinku
A = np.array([[54, 61, 35, 4], [1, 11, 15, 93]])
print(A)
b = np.array([35, 78])
print(b)
x = np.linalg.lstsq(A, b, rcond=None)[0]
res = np.linalg.norm(b - A @ x)
print(res)
print("{:.5f}".format(res)) 

[[54 61 35  4]
 [ 1 11 15 93]]
[35 78]
4.263256414560601e-14
0.00000


In [7]:
# Dla macierzy A wypisz wielomian charakterystyczny
A = np.array([[0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [3, 9, -4, 10]])
print(A)
poly = np.poly(A)
print(poly)

[[ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]
 [ 3  9 -4 10]]
[  1. -10.   4.  -9.  -3.]


In [8]:
# Rozwiąż równanie nieliniowe używając funkcji scipy.optimize.fsolve, 
# podaj wynik z dokładności do 5 miejsc po przecinku
# Dla warunku początkowego x0 = 0
from scipy.optimize import fsolve
root = fsolve(lambda x: np.exp(2*x)+x, x0=[0])
print(root)

[-0.42630275]


In [15]:
# Korzystając z funkcji scipy.interpolate.barycentric_interpolate podaj wartość 
# (z dokładnością do 3 miejsc po przecinku ) interpolacji dla funkcji -sin(x) + x**3 w punkcie 0.27662521902624004
# obliczonej na 13 węzłach Czybyszewa
from scipy.interpolate import barycentric_interpolate

# config - start
x=0.27662521902624004
interpolation_nodes_number=13
fun = lambda x: -np.sin(x) + x**3
# config - end

xch = np.cos(np.linspace(1,interpolation_nodes_number,interpolation_nodes_number)*np.pi/interpolation_nodes_number)

fValsX = fun(x)
fValsXch = fun(xch)

print(barycentric_interpolate(xch, fValsXch, x))

-0.1669825792315721


In [18]:
# Znajdź miejsca zerowe wielomianu charakterystycznego macierzy,
# Wynik podaj w porządku niemalejącym zakrąglone do liczb całkowitych w postaci [x, y, z, ...]
A= [[ 0, 1, 0, 0], [ 0, 0, 1, 0], [ 0, 0, 0, 1], [ 0, -120, -74, -15]]
eig = np.linalg.eigvals(A)
print(np.sort(eig))

[-6. -4.  3.  5.]


In [13]:
# Podaj mantysę liczby 7.216209369692788 z dokładności do 5 miejsc po przecinku.
print(math.frexp(7.216209369692788))
# mantysa to 0.9020261712115984, cecha to 3
print(f"Sprawdzenie: {0.9020261712115984 * 2**3 }")

(0.9020261712115984, 3)
Sprawdzenie: 7.216209369692788


In [14]:
# Dokonaj rozkładu macierzy A za pomocą metody QR i podaj wartość pola 
# R[1,3] z dokładnością do 5 miejsc po przecinku
A = np.array([[1, 3, 5, 6], [7, 4, 3, 4], [4, 1, 4, 7]])
print(A)
Q, R = np.linalg.qr(A)
print(R[1,3])

[[1 3 5 6]
 [7 4 3 4]
 [4 1 4 7]]
2.977502095901732


In [ ]:
# Dokonaj rozkładu macierzy A za pomocą metody QR i podaj wartość pola R[1,3] z dokładnością do 5 miejsc po przecinku
# na przedziale [51,54] dla 560 punktów wygenerowanych przy pomocy funkcji linspace. 
# Wynik podaj z dokładnością do 5 miejsca po przecinku.
fun = lambda x: np.sqrt(x + 1) * x

x = np.linspace(51, 54, 560)
y = fun(x)
integral = sp.integrate.trapz(y, x)
print(integral)